# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import bookings_pb2 as bookings__pb2
from proto  import service_discovery_pb2 as service__discovery__pb2


class BookingsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookScooter = channel.unary_unary(
                '/BookingsService/BookScooter',
                request_serializer=bookings__pb2.BookScooterRequest.SerializeToString,
                response_deserializer=bookings__pb2.BookScooterResponse.FromString,
                )
        self.EndRide = channel.unary_unary(
                '/BookingsService/EndRide',
                request_serializer=bookings__pb2.EndRideRequest.SerializeToString,
                response_deserializer=bookings__pb2.BookScooterResponse.FromString,
                )
        self.GetBooking = channel.unary_unary(
                '/BookingsService/GetBooking',
                request_serializer=bookings__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=bookings__pb2.BookScooterResponse.FromString,
                )
        self.GetAllBookings = channel.unary_unary(
                '/BookingsService/GetAllBookings',
                request_serializer=service__discovery__pb2.Empty.SerializeToString,
                response_deserializer=bookings__pb2.GetAllBookingsResponse.FromString,
                )


class BookingsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookScooter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookScooter': grpc.unary_unary_rpc_method_handler(
                    servicer.BookScooter,
                    request_deserializer=bookings__pb2.BookScooterRequest.FromString,
                    response_serializer=bookings__pb2.BookScooterResponse.SerializeToString,
            ),
            'EndRide': grpc.unary_unary_rpc_method_handler(
                    servicer.EndRide,
                    request_deserializer=bookings__pb2.EndRideRequest.FromString,
                    response_serializer=bookings__pb2.BookScooterResponse.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=bookings__pb2.GetBookingRequest.FromString,
                    response_serializer=bookings__pb2.BookScooterResponse.SerializeToString,
            ),
            'GetAllBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=service__discovery__pb2.Empty.FromString,
                    response_serializer=bookings__pb2.GetAllBookingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookingsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookingsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookScooter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookingsService/BookScooter',
            bookings__pb2.BookScooterRequest.SerializeToString,
            bookings__pb2.BookScooterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookingsService/EndRide',
            bookings__pb2.EndRideRequest.SerializeToString,
            bookings__pb2.BookScooterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookingsService/GetBooking',
            bookings__pb2.GetBookingRequest.SerializeToString,
            bookings__pb2.BookScooterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookingsService/GetAllBookings',
            service__discovery__pb2.Empty.SerializeToString,
            bookings__pb2.GetAllBookingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
