# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import bookings_pb2 as bookings__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='coordinator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63oordinator.proto\x1a\x0e\x62ookings.proto2y\n\x0b\x43oordinator\x12\x38\n\x0b\x42ookScooter\x12\x13.BookScooterRequest\x1a\x14.BookScooterResponse\x12\x30\n\x07\x45ndRide\x12\x0f.EndRideRequest\x1a\x14.BookScooterResponseb\x06proto3'
  ,
  dependencies=[bookings__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COORDINATOR = _descriptor.ServiceDescriptor(
  name='Coordinator',
  full_name='Coordinator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=37,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='BookScooter',
    full_name='Coordinator.BookScooter',
    index=0,
    containing_service=None,
    input_type=bookings__pb2._BOOKSCOOTERREQUEST,
    output_type=bookings__pb2._BOOKSCOOTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndRide',
    full_name='Coordinator.EndRide',
    index=1,
    containing_service=None,
    input_type=bookings__pb2._ENDRIDEREQUEST,
    output_type=bookings__pb2._BOOKSCOOTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATOR)

DESCRIPTOR.services_by_name['Coordinator'] = _COORDINATOR

# @@protoc_insertion_point(module_scope)
