services:
  mysqldb:
    image: mysql:8.0
    container_name: scooters_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./ScootersService/dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: scootersdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - scooter_rent

networks:
  scooter_rent:
    driver: bridge
