services:
  scooters-management:
    container_name: scooters-management
    build: ./ScootersService
    image: scooters_management:1.0
    restart: always
    volumes:
      - ./ScootersService:/user/src
    ports:
      - 3000:3000
      - 30001:30001
    expose:
      - 3000
      - 30001
    environment:
      DB_HOST: scootersdb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'password'
      DB_NAME: scootersdb
      DB_CONNECTION_LIMIT: 10
      SERVICE_NAME: scooters-management
      SERVER_PORT: 3000
      SERVICE_DISCOVERY_PORT: 2000
      SERVICE_DISCOVERY_HOST: service-discovery
    depends_on:
      - scootersdb
      - service-discovery
    networks:
      - scooter-rent

  scootersdb:
    image: mysql:8.0
    container_name: scooters-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./ScootersService/dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: scootersdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: scootersdb
    networks:
      - scooter-rent

  bookings-management:
    container_name: bookings-management
    build: ./BookingService
    image: bookings_management:1.0
    restart: always
    volumes:
      - ./BookingService:/user/src
    ports:
      - 3001:3001
    expose:
      - 3001
    environment:
      DB_HOST: bookingsdb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'password'
      DB_NAME: bookingsdb
      DB_CONNECTION_LIMIT: 10
      SERVICE_NAME: bookings-management
      SERVER_PORT: 3001
      SERVICE_DISCOVERY_PORT: 2000
      SERVICE_DISCOVERY_HOST: service-discovery
      TIMEOUT: 3000
    depends_on:
      - bookingsdb
      - service-discovery
      - scooters-management
    networks:
      - scooter-rent

  bookingsdb:
    image: mysql:8.0
    container_name: bookings-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./BookingService/dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/project/database1:/var/lib/mysql
    ports:
      - 3305:3306
    expose:
      - 3305
    environment:
      MYSQL_DATABASE: bookingsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: bookingsdb
    networks:
      - scooter-rent

  service-discovery:
    container_name: service-discovery
    build: ./ServiceDiscovery
    image: service-discovery:1.0
    restart: always
    volumes:
      - ./ServiceDiscovery:/app
    ports:
      - 2000:2000
    expose:
      - 2000
    environment:
      SERVICE_NAME: service-discovery
      SERVER_PORT: 2000
    networks:
      - scooter-rent

  api-gateway:
    container_name: api-gateway
    build: ./ApiGateway
    image: api-gateway:1.0
    restart: always
    volumes:
      - ./ApiGateway:/app
    ports:
      - 2050:2050
    expose:
      - 2050
    environment:
      SERVICE_NAME: api-gateway
      SERVER_PORT: 2050
    networks:
      - scooter-rent

  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - scooter-rent

networks:
  scooter-rent:
    driver: bridge

volumes:
  redis-data:
