# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service_discovery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/service_discovery.proto\"?\n\x0bServiceInfo\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"&\n\x0eServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1e\n\x0cHealthStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x92\x01\n\x0fServiceRegistry\x12\'\n\x0fRegisterService\x12\x0c.ServiceInfo\x1a\x06.Empty\x12\x30\n\x0f\x44iscoverService\x12\x0f.ServiceRequest\x1a\x0c.ServiceInfo\x12$\n\x0b\x43heckHealth\x12\x06.Empty\x1a\r.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_discovery_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVICEINFO']._serialized_start=33
  _globals['_SERVICEINFO']._serialized_end=96
  _globals['_SERVICEREQUEST']._serialized_start=98
  _globals['_SERVICEREQUEST']._serialized_end=136
  _globals['_EMPTY']._serialized_start=138
  _globals['_EMPTY']._serialized_end=145
  _globals['_HEALTHSTATUS']._serialized_start=147
  _globals['_HEALTHSTATUS']._serialized_end=177
  _globals['_SERVICEREGISTRY']._serialized_start=180
  _globals['_SERVICEREGISTRY']._serialized_end=326
# @@protoc_insertion_point(module_scope)
